// Generated by gencpp from file oct_msgs/DepthRequest.msg
// DO NOT EDIT!


#ifndef OCT_MSGS_MESSAGE_DEPTHREQUEST_H
#define OCT_MSGS_MESSAGE_DEPTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace oct_msgs
{
template <class ContainerAllocator>
struct DepthRequest_
{
  typedef DepthRequest_<ContainerAllocator> Type;

  DepthRequest_()
    {
    }
  DepthRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::oct_msgs::DepthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oct_msgs::DepthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DepthRequest_

typedef ::oct_msgs::DepthRequest_<std::allocator<void> > DepthRequest;

typedef boost::shared_ptr< ::oct_msgs::DepthRequest > DepthRequestPtr;
typedef boost::shared_ptr< ::oct_msgs::DepthRequest const> DepthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::oct_msgs::DepthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::oct_msgs::DepthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace oct_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::oct_msgs::DepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oct_msgs::DepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oct_msgs::DepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oct_msgs::DepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oct_msgs::DepthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oct_msgs::DepthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::oct_msgs::DepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::oct_msgs::DepthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::oct_msgs::DepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "oct_msgs/DepthRequest";
  }

  static const char* value(const ::oct_msgs::DepthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::oct_msgs::DepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::oct_msgs::DepthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::oct_msgs::DepthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oct_msgs::DepthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::oct_msgs::DepthRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OCT_MSGS_MESSAGE_DEPTHREQUEST_H
