// Generated by gencpp from file oct_msgs/DepthResponse.msg
// DO NOT EDIT!


#ifndef OCT_MSGS_MESSAGE_DEPTHRESPONSE_H
#define OCT_MSGS_MESSAGE_DEPTHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>

namespace oct_msgs
{
template <class ContainerAllocator>
struct DepthResponse_
{
  typedef DepthResponse_<ContainerAllocator> Type;

  DepthResponse_()
    : depth()  {
    }
  DepthResponse_(const ContainerAllocator& _alloc)
    : depth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::oct_msgs::DepthResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oct_msgs::DepthResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DepthResponse_

typedef ::oct_msgs::DepthResponse_<std::allocator<void> > DepthResponse;

typedef boost::shared_ptr< ::oct_msgs::DepthResponse > DepthResponsePtr;
typedef boost::shared_ptr< ::oct_msgs::DepthResponse const> DepthResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::oct_msgs::DepthResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::oct_msgs::DepthResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::oct_msgs::DepthResponse_<ContainerAllocator1> & lhs, const ::oct_msgs::DepthResponse_<ContainerAllocator2> & rhs)
{
  return lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::oct_msgs::DepthResponse_<ContainerAllocator1> & lhs, const ::oct_msgs::DepthResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace oct_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::oct_msgs::DepthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oct_msgs::DepthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oct_msgs::DepthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oct_msgs::DepthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oct_msgs::DepthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oct_msgs::DepthResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::oct_msgs::DepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f70a1f9db66aa7e4df2419db894e774";
  }

  static const char* value(const ::oct_msgs::DepthResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f70a1f9db66aa7eULL;
  static const uint64_t static_value2 = 0x4df2419db894e774ULL;
};

template<class ContainerAllocator>
struct DataType< ::oct_msgs::DepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "oct_msgs/DepthResponse";
  }

  static const char* value(const ::oct_msgs::DepthResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::oct_msgs::DepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 depth\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::oct_msgs::DepthResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::oct_msgs::DepthResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oct_msgs::DepthResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::oct_msgs::DepthResponse_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCT_MSGS_MESSAGE_DEPTHRESPONSE_H
