
classdef DepthResponse < ros.Message
    %DepthResponse MATLAB implementation of oct_msgs/DepthResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'oct_msgs/DepthResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1f70a1f9db66aa7e4df2419db894e774' % The MD5 Checksum of the message definition
        PropertyList = { 'Depth' } % List of non-constant message properties
        ROSPropertyList = { 'depth' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Float64' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Depth
    end
    methods
        function set.Depth(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Float64'};
            validateattributes(val, validClasses, validAttributes, 'DepthResponse', 'Depth')
            obj.Depth = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.oct_msgs.DepthResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.oct_msgs.DepthResponse(strObj);
        end
    end
end
