// Generated by gencpp from file oct_msgs/Depth.msg
// DO NOT EDIT!


#ifndef OCT_MSGS_MESSAGE_DEPTH_H
#define OCT_MSGS_MESSAGE_DEPTH_H

#include <ros/service_traits.h>


#include <oct_msgs/DepthRequest.h>
#include <oct_msgs/DepthResponse.h>


namespace oct_msgs
{

struct Depth
{

typedef DepthRequest Request;
typedef DepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Depth
} // namespace oct_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::oct_msgs::Depth > {
  static const char* value()
  {
    return "1f70a1f9db66aa7e4df2419db894e774";
  }

  static const char* value(const ::oct_msgs::Depth&) { return value(); }
};

template<>
struct DataType< ::oct_msgs::Depth > {
  static const char* value()
  {
    return "oct_msgs/Depth";
  }

  static const char* value(const ::oct_msgs::Depth&) { return value(); }
};


// service_traits::MD5Sum< ::oct_msgs::DepthRequest> should match
// service_traits::MD5Sum< ::oct_msgs::Depth >
template<>
struct MD5Sum< ::oct_msgs::DepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::oct_msgs::Depth >::value();
  }
  static const char* value(const ::oct_msgs::DepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::oct_msgs::DepthRequest> should match
// service_traits::DataType< ::oct_msgs::Depth >
template<>
struct DataType< ::oct_msgs::DepthRequest>
{
  static const char* value()
  {
    return DataType< ::oct_msgs::Depth >::value();
  }
  static const char* value(const ::oct_msgs::DepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::oct_msgs::DepthResponse> should match
// service_traits::MD5Sum< ::oct_msgs::Depth >
template<>
struct MD5Sum< ::oct_msgs::DepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::oct_msgs::Depth >::value();
  }
  static const char* value(const ::oct_msgs::DepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::oct_msgs::DepthResponse> should match
// service_traits::DataType< ::oct_msgs::Depth >
template<>
struct DataType< ::oct_msgs::DepthResponse>
{
  static const char* value()
  {
    return DataType< ::oct_msgs::Depth >::value();
  }
  static const char* value(const ::oct_msgs::DepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OCT_MSGS_MESSAGE_DEPTH_H
