// Generated by gencpp from file simple_msgs/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SIMPLE_MSGS_MESSAGE_ADDTWOINTS_H
#define SIMPLE_MSGS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <simple_msgs/AddTwoIntsRequest.h>
#include <simple_msgs/AddTwoIntsResponse.h>


namespace simple_msgs
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace simple_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_msgs::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::simple_msgs::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::simple_msgs::AddTwoInts > {
  static const char* value()
  {
    return "simple_msgs/AddTwoInts";
  }

  static const char* value(const ::simple_msgs::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::simple_msgs::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::simple_msgs::AddTwoInts >
template<>
struct MD5Sum< ::simple_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::simple_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_msgs::AddTwoIntsRequest> should match
// service_traits::DataType< ::simple_msgs::AddTwoInts >
template<>
struct DataType< ::simple_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::simple_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::simple_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_msgs::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::simple_msgs::AddTwoInts >
template<>
struct MD5Sum< ::simple_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::simple_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_msgs::AddTwoIntsResponse> should match
// service_traits::DataType< ::simple_msgs::AddTwoInts >
template<>
struct DataType< ::simple_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::simple_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::simple_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_MSGS_MESSAGE_ADDTWOINTS_H
